version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - BOT_TOKEN
      - BOT_PREFIX
      - API_KEY
      - API_URL
    restart: unless-stopped
